# Site settings
title: 
header-img: img/home-bg.png
email: sean@seanaltemose.com
copyright_name: saltemose
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  saltemose
learn_profile: saltemose
email_username: sean@seanaltemose.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
